# Generated by Django 4.1.3 on 2022-11-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_alter_book_category'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='books',
            field=models.ManyToManyField(to='library.book', verbose_name='books'),
        ),
    ]
