# Generated by Django 4.1.3 on 2022-11-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_libraryuser_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='profile_pic',
            field=models.ImageField(default='default_pic.jpg', upload_to='', verbose_name='profile picture'),
        ),
    ]
